version: '2'

services:
  vdjbase_flask:
    image: my_flask
    container_name: vdjbase_flask
    volumes:
        - /root/digby_docker/config/flask:/config
        - /root/digby_docker/backup:/backup
        - /root/digby_docker/study_data:/study_data
    restart: unless-stopped 
networks:
    default:
        external: true
        name: digby_network
