version: '2'

services:
  vdjbase_flask:
    image: vdjbase_flask
    container_name: vdjbase_flask
    volumes:
        - /root/digby_docker/config/flask:/config
        - /root/digby_docker/backup:/backup
        - /root/digby_docker/study_data:/study_data
    restart: unless-stopped 
    environment:
        - GUNICORN_WORKERS=1
        - CELERY_WORKERS=1   
    ulimits:
        nofile:
            soft: "65536"
            hard: "65536"
networks:
    default:
        external: true
        name: digby_network
